### ISSUE TITLE
Billboard functionality with only Headline or only Teaser

### ISSUE THREAD

**Issue by dajoturner** [ucsc/webtemplates2014#331] opened 2014-09-04 19:11 UTC
Right now, the billboard doesn't show if you only have a Headline, or only a Teaser. Need to develop use cases and style accordingly.

**Comment by dajoturner** [comment] 2015-02-24 18:56
We decided this is something Rob needs to do for the project. Reopening.

**Comment by knice** [comment] 2015-04-10 14:57
@dajoturner is this a duplicate of #337?

**Comment by dajoturner** [comment] 2015-04-11 19:05
@knice No, I don't think so. To clarify:

1. #337 was about the whole billboard acting as a link, in the event that there is a link in the link field, but no link text provided. In other words, if I put in a link but no link text, the whole billboard becomes the link. I think you completed this.

2.  #331 is about when people only use a Headline OR Teaser Text. Currently, if you only provide one of those elements, neither of them shows - you have to provide both to see either. At one point you said that was the desired behavior - they don't look good with only one. Then we reopened it for some reason that I can't recall, but the implication was a decision that they CAN provide only one element and have it show.

Up to you what the final behavior is here. If we want to go back to "that's how it's supposed to be," then I think we can close this. Otherwise, you'd need to make the Headline and Teaser text independent - if it has text, that text shows.

Your call.
-D

**Comment by knice** [comment] 2015-04-13 20:02
Thank you for the clarification, David. That makes sense. 

1. #337 I haven't dealt with this yet. I am working on it today. The functional change will be this: if there is a link (to a page, system symlink, or plain text URL), the entire billboard will become linked. If there is link text, it will be included in the colored area as it did before, but _the entire billboard will still be a link_. This makes things more simple for the end user: Either the entire billboard is linked or it isn't (see diagram below). This is implemented on stage. I'll be testing shortly and then moving to prod by EOD.

2. #331 I'm going to close this because it is still the case that having a headline AND a teaser is mandatory. We simply haven't designed for both to be _optional_. If we do eventually create designs for that scenario, it'll be added as an enhancement.

![napkin 2 04-13-15 1 00 09 pm](https://cloud.githubusercontent.com/assets/36719/7124381/41455c04-e1dd-11e4-9433-a9b72ec05aea.png)

**Comment by knice** [comment] 2015-04-13 20:15
For @teresasilva71, I suspect you might need to update your help documentation. 

- Previously: If you had a link with a headline and teaser in your billboard, you had to include link text.
- Now: If you have a link in your billboard, the entire billboard is a link. If you have a headline and a teaser, the *link text* field is optional.

**Comment by knice** [comment] 2015-04-13 20:22
Closing this issue. Headlines must be accompanied by a teaser (and vice-versa) or neither will show.

**Closed by knice** 2015-04-13 20:22 UTC
Labels: billboards, client-impact, enhancement, Important

**Comment by dajoturner** [comment] 2015-04-13 20:44
WCMS has updated prompt text explaining that both are required - sweet!
